version: "3.0"
services:
  area-frontend:
    build: ./react_front/Area
    ports:
      - "8081:19006"
    depends_on:
      - area-backend
    entrypoint: ["yarn", "web"]
    volumes:
      - "./react_front/Area:/var/app"

  area-mobile:
    build: ./react_front/Area
    ports:
      - "8082:19000"
    depends_on:
      - area-backend
    entrypoint: ["yarn", "android"]
    volumes:
      - "./react_front/Area:/var/app"

  area-backend:
    build: ./backend/
    volumes:
      - "./logs/backend:/var/logs"
      # - "./backend:/var/app"
    ports:
      - "8080:5000"
    depends_on:
      - redis
    networks:
      - redis-net
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

  redis:
    image: redislabs/rejson:latest
    hostname: redis
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --appendonly yes
    networks:
      - redis-net
    volumes:
      - ./redis-data:/data
      - ./redis-dump:/var/lib/redis-dump

volumes:
  redis-data:
  redis-dump:

networks:
  redis-net:
