FROM node:14.15

WORKDIR /var/app

COPY package.json .

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java && \
    apt-get install -y openjdk-8-jdk && \
    npm install -g turtle-cli --unsafe-perm && \
    yarn global add expo-cli && \
    yarn add expo && \
    yarn install

COPY . .

RUN /bin/bash ./android-build.sh

CMD [ "/bin/bash", "-c", "cp /root/expo-apps/*.apk /var/app/android-build/client.apk" ]